version: "3.3"  # optional since v1.27.0
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - config=server.conf
        - ip=10.33.7.1/24
    volumes:
      - ..:/code
    cap_add:
      - net_admin
      - sys_module
  peer1:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - config=peer1.conf
        - ip=10.33.7.2/24
    cap_add:
      - net_admin
      - sys_module
  peer2:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - config=peer2.conf
        - ip=10.33.7.3/24
    cap_add:
      - net_admin
      - sys_module